import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Navbar } from "@/components/ui/shared/navbar";
import { getMe } from "../../service/getMe";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({ children }: LayoutProps<"/">) {
  const user= await getMe()
  return (
    <html
      lang="en"

    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar user={user}/>
        <Toaster/> */}
        {children}</body>
    </html>
  );
}
